@startuml
class ClassicFurnitureFactory {
    + CreateCabinet() : IFurniture
    + CreateChair() : IFurniture
    + CreateDiningTable() : IFurniture
}
IFurnitureFactory <|-- ClassicFurnitureFactory
@enduml
