@startuml
class ScandinavianFurnitureFactory {
    + CreateCabinet() : IFurniture
    + CreateChair() : IFurniture
    + CreateDiningTable() : IFurniture
}
IFurnitureFactory <|-- ScandinavianFurnitureFactory
@enduml
