@startuml
!include .\\AbstractFactoryByStyle\Program.puml
!include .\\AbstractFactoryTwoByFurniture\Program.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Program.puml
!include .\\WithoutAbstractFactory\Program.puml
!include .\\AbstractFactoryByStyle\Classic\ClassicCabinet.puml
!include .\\AbstractFactoryByStyle\Classic\ClassicChair.puml
!include .\\AbstractFactoryByStyle\Classic\ClassicDiningTable.puml
!include .\\AbstractFactoryByStyle\Classic\ClassicFurnitureFactory.puml
!include .\\AbstractFactoryByStyle\Contemporary\ContemporaryCabinet.puml
!include .\\AbstractFactoryByStyle\Contemporary\ContemporaryChair.puml
!include .\\AbstractFactoryByStyle\Contemporary\ContemporaryDiningTable.puml
!include .\\AbstractFactoryByStyle\Contemporary\ContemporaryFurnitureFactory.puml
!include .\\AbstractFactoryByStyle\Interfaces\IFurniture.puml
!include .\\AbstractFactoryByStyle\Interfaces\IFurnitureFactory.puml
!include .\\AbstractFactoryByStyle\Properties\AssemblyInfo.puml
!include .\\AbstractFactoryByStyle\Scandinavian\ScandinavianCabinet.puml
!include .\\AbstractFactoryByStyle\Scandinavian\ScandinavianChair.puml
!include .\\AbstractFactoryByStyle\Scandinavian\ScandinavianDiningTable.puml
!include .\\AbstractFactoryByStyle\Scandinavian\ScandinavianFurnitureFactory.puml
!include .\\AbstractFactoryTwoByFurniture\Cabinet\CabinetFactory.puml
!include .\\AbstractFactoryTwoByFurniture\Cabinet\ClassicCabinet.puml
!include .\\AbstractFactoryTwoByFurniture\Cabinet\ContemporaryCabinet.puml
!include .\\AbstractFactoryTwoByFurniture\Cabinet\ScandinavianCabinet.puml
!include .\\AbstractFactoryTwoByFurniture\Chair\ChairFactory.puml
!include .\\AbstractFactoryTwoByFurniture\Chair\ClassicChair.puml
!include .\\AbstractFactoryTwoByFurniture\Chair\ContemporaryChair.puml
!include .\\AbstractFactoryTwoByFurniture\Chair\ScandinavianChair.puml
!include .\\AbstractFactoryTwoByFurniture\DiningTable\ClassicDiningTable.puml
!include .\\AbstractFactoryTwoByFurniture\DiningTable\ContemporaryDiningTable.puml
!include .\\AbstractFactoryTwoByFurniture\DiningTable\DiningTableFactory.puml
!include .\\AbstractFactoryTwoByFurniture\DiningTable\ScandinavianDiningTable.puml
!include .\\AbstractFactoryTwoByFurniture\Interfaces\IStyleFactory.puml
!include .\\AbstractFactoryTwoByFurniture\Interfaces\IStyles.puml
!include .\\AbstractFactoryTwoByFurniture\Properties\AssemblyInfo.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\BaseClasses\Furniture.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\BaseClasses\FurnitureFactory.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Classic\ClassicCabinet.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Classic\ClassicChair.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Classic\ClassicDiningTable.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Classic\ClassicFactory.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Contemporary\ContemporaryCabinet.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Contemporary\ContemporaryChair.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Contemporary\ContemporaryDiningTable.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Contemporary\ContemporaryFactory.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Properties\AssemblyInfo.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Scandinavian\ScandinavianCabinet.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Scandinavian\ScandinavianChair.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Scandinavian\ScandinavianDiningTable.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\Scandinavian\ScandinavianFactory.puml
!include .\\WithoutAbstractFactory\Classic\ClassicCabinet.puml
!include .\\WithoutAbstractFactory\Classic\ClassicChair.puml
!include .\\WithoutAbstractFactory\Classic\ClassicDiningTable.puml
!include .\\WithoutAbstractFactory\Contemporary\ContemporaryCabinet.puml
!include .\\WithoutAbstractFactory\Contemporary\ContemporaryChair.puml
!include .\\WithoutAbstractFactory\Contemporary\ContemporaryDiningTable.puml
!include .\\WithoutAbstractFactory\Properties\AssemblyInfo.puml
!include .\\WithoutAbstractFactory\Scandinavian\ScandinavianCabinet.puml
!include .\\WithoutAbstractFactory\Scandinavian\ScandinavianChair.puml
!include .\\WithoutAbstractFactory\Scandinavian\ScandinavianDiningTable.puml
!include .\\AbstractFactoryByStyle\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\AbstractFactoryTwoByFurniture\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\AbstractFactoryWith_InheritanceAndBaseClass\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\WithoutAbstractFactory\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
@enduml
